#!/bin/sh

### BEGIN INIT INFO
# Provides:
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Small busybox ntp server
# Description:       busybox-ntpd is a small and fast busybox ntp applet
### END INIT INFO

DAEMON=/usr/sbin/ntpd
NAME=ntpd
DESC="Busybox NTP Daemon"
source /etc/busybox-ntpd.conf
ARGS="-p $PEER"

test -f $DAEMON || exit 0

set -e

case "$1" in
    start)
        if [ -z "$PEER" ]; then
            echo "PEER needs to be specified"
        else
            start-stop-daemon -S -b -n $NAME -a $DAEMON -- $ARGS
            echo "ntpd start: done."
        fi
        ;;
    stop)
        echo -n "stopping $DESC: $NAME... "
        start-stop-daemon -K -n $NAME
        echo "ntpd stop: done."
        ;;
    restart)
        echo "restarting $DESC: $NAME... "
        $0 stop
        $0 start
        echo "ntpd restart: done."
        ;;
    reload)
        echo -n "reloading $DESC: $NAME... "
        killall -HUP $(basename ${DAEMON})
        echo "ntpd reload: done."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
        ;;
esac

exit 0
